### ISSUE TITLE
pages error

### ISSUE THREAD

**Issue by imoon** [peterkeen/sites#10]
Hi,

Everytime I try to access the "all" pages I get this error

```
Gollum::InvalidGitRepositoryError at /myfirstsite/pages
Gollum::InvalidGitRepositoryError
file: git_access.rb location: rescue in initialize line: 19

sites/middleware.rb in call
      @app.call(env)
```

Any ideas? 

Also, I have read all of your documentation and I am at a loss of how to get the cname feature to work. Do you have a more complete example?

Thanks,
Steven

**Comment by peterkeen** [comment]
Hi Steven,

Could you paste a few things for me? Specifically, I'd like to see the exact command line you're using to start sites and the exact URLs you're trying to access.

As for the CNAME feature, just create a wiki page named `cnames` and put one domain name per line in there (here's an example: https://raw.github.com/peterkeen/docverter.com/master/cnames.md), then point all of those domain names at the IP where your sites install is running, after configuring nginx for it to be the default server as described in the docs. For the docverter example, the relevant DNS records are

```
docverter.com.          300 IN  A   192.241.250.244
www.docverter.com.  300 IN  CNAME   sites.bugsplat.info.
sites.bugsplat.info.    300 IN  CNAME   web01.bugsplat.info.
web01.bugsplat.info.    300 IN  A   192.241.250.244
```

**Comment by evolve2k** [comment]
Hey Peter

I can reproduce this error and getting the same message:

```
"Gollum::InvalidGitRepositoryError at /mywebsite/pages"
```

> Specifically, I'd like to see the exact command line you're using to start sites and the exact URLs you're trying to access.

I'm using zsh in OSX, command:

```
$ rackup 
```

Exact url Im accessing is:

```
http://localhost:9292/myfirstsite/pages
```

Error messages from the logs:

```
Gollum::InvalidGitRepositoryError - Gollum::InvalidGitRepositoryError:
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/gollum-lib-1.0.9/lib/gollum-lib/git_access.rb:19:in `rescue in initialize'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/gollum-lib-1.0.9/lib/gollum-lib/git_access.rb:16:in `initialize'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/gollum-lib-1.0.9/lib/gollum-lib/wiki.rb:204:in `new'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/gollum-lib-1.0.9/lib/gollum-lib/wiki.rb:204:in `initialize'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/bundler/gems/gollum-b836b0e273d8/lib/gollum/app.rb:415:in `new'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/bundler/gems/gollum-b836b0e273d8/lib/gollum/app.rb:415:in `block in <class:App>'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1592:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1592:in `block in compile!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `[]'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (3 levels) in route!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:976:in `route_eval'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (2 levels) in route!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:997:in `block in process_route'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `catch'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `process_route'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:955:in `block in route!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `each'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `route!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1067:in `block in dispatch!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1064:in `dispatch!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `block in call!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `call!'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:877:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/auth/basic.rb:25:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-protection-1.5.1/lib/rack/protection/xss_header.rb:18:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-protection-1.5.1/lib/rack/protection/path_traversal.rb:16:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-protection-1.5.1/lib/rack/protection/json_csrf.rb:18:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-protection-1.5.1/lib/rack/protection/base.rb:50:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-protection-1.5.1/lib/rack/protection/base.rb:50:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-protection-1.5.1/lib/rack/protection/frame_options.rb:31:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/show_exceptions.rb:21:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:180:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:2004:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `block in call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1778:in `synchronize'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `call'
    /Users/richie/Projects/sites/middleware.rb:59:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/deflater.rb:25:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/puma-2.7.1/lib/puma/rack_patch.rb:13:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/puma-2.7.1/lib/puma/server.rb:486:in `handle_request'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/puma-2.7.1/lib/puma/server.rb:357:in `process_client'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/puma-2.7.1/lib/puma/server.rb:250:in `block in run'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/puma-2.7.1/lib/puma/thread_pool.rb:92:in `call'
    /Users/richie/.rvm/gems/ruby-2.0.0-p0/gems/puma-2.7.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
127.0.0.1 - example [16/Jan/2014 15:38:05] "GET /pages HTTP/1.1" 500 - 0.1093
127.0.0.1 - example [16/Jan/2014 15:38:06] "GET /__sinatra__/500.png HTTP/1.1" 302 - 0.0099
127.0.0.1 - example [16/Jan/2014 15:38:06] "GET /create/__sinatra__/500.png HTTP/1.1" 200 - 0.0602
127.0.0.1 - example [16/Jan/2014 15:38:06] "GET /favicon.ico HTTP/1.1" 200 - 0.0046
```

**Comment by ghost** [comment]
I'm getting it too
https://www.evernote.com/shard/s173/sh/7153c1af-932a-4508-91f6-bd1186c9200e/c718a1e931ced5923ed391f7a0da8390
after accessing All in gollum's editor.
